// const PLATFORM_URL='https://sealable-maci-nonmeteorologic.ngrok-free.dev'
// const LINKEDIN_URL='https://www.linkedin.com'
// const VOYAGER_API=LINKEDIN_URL+'/voyager/api'
const PLATFORM_URL='https://linkedempire.com'
const LINKEDIN_URL='https://www.linkedin.com'
const VOYAGER_API=LINKEDIN_URL+'/voyager/api'